#!/usr/bin/env python3
    """
    Context Refresh Script
    
    Updates evergreen context files for AI operators.
    """
    
    import sys
    from pathlib import Path
    
    # Add core to path
    sys.path.insert(0, str(Path(__file__).parent.parent / "core"))
    
    from j5a_memory import J5AMemory
    
    
    def refresh_priorities():
        """Update current priorities"""
        priorities = """# Current Priorities
    
    **Updated:** Auto-generated by refresh_context.py
    
    ## High Priority
    - System stability and reliability
    - Constitutional compliance
    - Resource stewardship
    
    ## Medium Priority
    - Feature development
    - Documentation updates
    
    ## Low Priority
    - Experimental features
    """
        return priorities
    
    
    def refresh_projects():
        """Update active projects"""
        projects = """# Active Projects
    
    **Updated:** Auto-generated by refresh_context.py
    
    ## Current Projects
    1. Beyond RAG Implementation
    2. Autonomous Workflow System
    3. Constitutional Framework Integration
    """
        return projects
    
    
    def main():
        """Main entry point"""
        print("Refreshing context files...")
    
        memory = J5AMemory()
    
        # Update priorities
        memory.update_context('priorities', refresh_priorities())
        print("✅ Updated priorities")
    
        # Update projects
        memory.update_context('projects', refresh_projects())
        print("✅ Updated projects")
    
        print("Context refresh complete!")
    
    
    if __name__ == "__main__":
        main()
    